development :
  adapter: postgresql
  encoding: unicode
  database: productapp_development
  pool: 5
  username: onemt
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: productapp_test
  pool: 5
  username: onemt
  password: 
